### ISSUE TITLE
Ports for iptables

### ISSUE THREAD

**Issue by hachel** [spocon/spocon#10]
Hi there,

sorry for the bother, could someone help with the ports for iptables? 

I've enabled a fixed port for avahi in the config file:
```
### Zeroconf ###
[zeroconf]
        # Listen on all interfaces (overrides `zeroconf.interfaces`)
        listenAll = true
        # Listen on these interfaces (comma separated list of names)
        interfaces = ""
        # Listen on this port (`-1` for random)
        listenPort = 5355
```
and opened that port as such:
```
:UDP - [0:0]
....
....
....
-A UDP -s 192.168.224.0/24 -p udp -m multiport --dports 5355 -j ACCEPT
```
but it doesn't show in my spotify app. As soon as I disable the firewall it shows up.

Any help would be appreciated

**Comment by devgianlu** [comment]
The Zeroconf port is actually TCP (do not use `5353` to avoid confusion), then you need to open the UDP port `5355` for mDNS.

**Comment by spocon** [comment]
Zero-configuration networking (zeroconf) is a set of technologies that automatically creates a usable computer network based on the Internet Protocol Suite (TCP/IP) 
source: https://en.wikipedia.org/wiki/Zero-configuration_networking

Have you tried to open the same port for tcp ?

**Comment by spocon** [comment]
@devgianlu damn you are fast ! :-P

**Comment by devgianlu** [comment]
I've added some clarification inside the README. 


> @devgianlu damn you are fast ! :-P

Yeah! I don't have much to do because of the quarantine.

**Comment by hachel** [comment]
> 
> 
> The Zeroconf port is actually TCP (do not use `5353` to avoid confusion), then you need to open the UDP port `5355` for mDNS.

I worked with opening the TCP port I've set in the config file, thank you very much.

It shouldn't be 5355 for mdns though, that's just what I've set it to in my config file. It should be 5353, no?

**Comment by devgianlu** [comment]
5355 is UDP and for mDNS, the port you select in the configuration is TCP and used for Spotify communication.

**Comment by hachel** [comment]
Here it says 5353: https://en.wikipedia.org/wiki/Multicast_DNS

```
An mDNS message is a multicast UDP packet sent using the following addressing:

    IPv4 address 224.0.0.251 or IPv6 address ff02::fb
    UDP port 5353
```
