### ISSUE TITLE
Stuck on "Connecting..."

### ISSUE THREAD

**Issue by arnib13** [spocon/spocon#12]
**Describe the bug**
After installing SpoCon using either the easy way or hard way, "SpoCon-Spotify" appears in available devices but playback is not transferred to RPI

**To Reproduce**
1. Install SpoCon on RPI
2. While playing music with Spotify Premium on Android, select "SpoCon-Spotify" in devices available
3. See "Connecting..." appear
4. Nothing happens, "Connecting..." seems to timeout. 

**Expected behavior**
Expected music to start playing on RPI

**Desktop (please complete the following information):**
Raspbian 9.11 stretch

**Smartphone (please complete the following information):**
 - Device: OnePlus6T
 - Spotify Premium account

**Additional context**
Might be a connection, but I'm trying this project since https://github.com/dtcooper/raspotify displays similar behaviour. Not sure when it stopped working, but it used work fine. 

On a bug there, this project is linked. https://github.com/dtcooper/raspotify/issues/241

**Comment by spocon** [comment]
hej arnib13,

can you give me the output of these two command in a terminal: 

`journalctl --no-pager -u -f spocon`

`service spocon status`

**Comment by arnib13** [comment]
journalctl --no-pager -u -f spocon
`Failed to add match 'spocon': Invalid argument`
service spocon status

`● spocon.service - SpoCon
   Loaded: loaded (/lib/systemd/system/spocon.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-22 13:36:09 GMT; 3min 22s ago
  Process: 2521 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
 Main PID: 2525 (java)
    Tasks: 17 (limit: 4915)
   CGroup: /system.slice/spocon.service
           └─2525 /usr/bin/java -jar /opt/spocon/librespot-java-core-v1.3.0.jar

mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1023 - Skipping SecretBlock
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1002 - Received LicenseVersion: 0
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:992 - Received CountryCode: IS
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1023 - Skipping ProductInfo
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1023 - Skipping LegacyWelcome
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 INFO  Session:1023 - Skipping UnknownData_AllZeros
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 TRACE MercuryClient:176 - Handling packet, cmd: MercuryEvent, seq: -7355736088356323328, flags: 1, parts: 1
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: -7355736088356323328, uri: hm://pusher/v1/connections/NmY0ODgzMDNjMmRmMjlkNTU3ZTk0MGUzM
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 DEBUG Session:1006 - Received 0x10: 23617DDEF86ADB25B67B4661ECB1476FCE6F4623
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 INFO  Session:957 - Skipping unknown command {cmd: 0x75, payload: 000000}
`

**Comment by spocon** [comment]
sorry it should be actually like this 
`
journalctl --no-pager -f -u spocon
`

my bad ;-)

**Comment by arnib13** [comment]
Hej!

 journalctl --no-pager -f -u spocon
`
-- Logs begin at Sun 2020-03-22 13:28:00 GMT. --
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1023 - Skipping SecretBlock
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1002 - Received LicenseVersion: 0
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:992 - Received CountryCode: IS
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1023 - Skipping ProductInfo
mar 22 13:38:26 raspberrypi java[2525]: 2020-03-22 13:38:26 INFO  Session:1023 - Skipping LegacyWelcome
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 INFO  Session:1023 - Skipping UnknownData_AllZeros
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 TRACE MercuryClient:176 - Handling packet, cmd: MercuryEvent, seq: -7355736088356323328, flags: 1, parts: 1
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: -7355736088356323328, uri: hm://pusher/v1/connections/NmY0ODgzMDNjMmRmMjlkNTU3ZTk0MGUzMmQ5ZDY3MWQyNjNlYWI4MCtBUCt0Y3A6Ly9nZXcxLWFjY2Vzc3BvaW50LWItdjRoeC5nZXcxLnNwb3RpZnkubmV0OjUwMDUrNzZBMjUwNTFCOTVBOTNENzM0NkYzQTVDRkUwQkVDRTNDQzA5ODRDNTg0RUJBMTdFN0EzNENCRTE1QTI2N0Y5NQ%3D%3D, code: 200, payload: []}
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 DEBUG Session:1006 - Received 0x10: 23617DDEF86ADB25B67B4661ECB1476FCE6F4623
mar 22 13:38:27 raspberrypi java[2525]: 2020-03-22 13:38:27 INFO  Session:957 - Skipping unknown command {cmd: 0x75, payload: 000000}
`

**Comment by spocon** [comment]
i think we need more logs. on this part i cant find anything wrong: 
Please do the same command , except -f 
`journalctl --no-pager -u spocon' 
or if you want to add it as file 
`journalctl --no-pager -f -u spocon > spocon.log`

**Comment by spocon** [comment]
@devgianlu can you have a look ?

**Comment by arnib13** [comment]
> i think we need more logs. on this part i cant find anything wrong:
> Please do the same command , except -f
> `journalctl --no-pager -u spocon`
> or if you want to add it as file
> `journalctl --no-pager -u spocon > spocon.log`

In this output there Exceptions, here they are: 

`mar 22 13:29:11 raspberrypi java[1075]: 2020-03-22 13:29:11 INFO  LineHelper:61 - Available mixers: 'PulseAudio Mixer', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'ALSA [plughw:0,2]'
mar 22 13:29:11 raspberrypi java[1075]: Exception in thread "zeroconf-client-29970921" java.lang.IllegalStateException: Failed opening line!
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:70)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.player.Player.<init>(Player.java:62)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.core.Session.authenticate(Session.java:297)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:332)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:38)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:396)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:471)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:379)
mar 22 13:29:11 raspberrypi java[1075]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
mar 22 13:29:11 raspberrypi java[1075]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
mar 22 13:29:11 raspberrypi java[1075]:         at java.lang.Thread.run(Thread.java:748)
mar 22 13:29:11 raspberrypi java[1075]: Caused by: javax.sound.sampled.LineUnavailableException
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
mar 22 13:29:11 raspberrypi java[1075]:         at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.player.PlayerRunner$Output.acquireLine(PlayerRunner.java:303)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.player.PlayerRunner$Output.<init>(PlayerRunner.java:282)
mar 22 13:29:11 raspberrypi java[1075]:         at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:68)
mar 22 13:29:11 raspberrypi java[1075]:         ... 10 more`

and

`mar 22 13:36:21 raspberrypi java[2525]: 2020-03-22 13:36:21 INFO  LineHelper:61 - Available mixers: 'PulseAudio Mixer', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'ALSA [plughw:0,2]'
mar 22 13:36:21 raspberrypi java[2525]: Exception in thread "zeroconf-client-21512987" java.lang.IllegalStateException: Failed opening line!
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:70)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.player.Player.<init>(Player.java:62)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.core.Session.authenticate(Session.java:297)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:332)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:38)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:396)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:471)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:379)
mar 22 13:36:21 raspberrypi java[2525]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
mar 22 13:36:21 raspberrypi java[2525]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
mar 22 13:36:21 raspberrypi java[2525]:         at java.lang.Thread.run(Thread.java:748)
mar 22 13:36:21 raspberrypi java[2525]: Caused by: javax.sound.sampled.LineUnavailableException
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
mar 22 13:36:21 raspberrypi java[2525]:         at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.player.PlayerRunner$Output.acquireLine(PlayerRunner.java:303)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.player.PlayerRunner$Output.<init>(PlayerRunner.java:282)
mar 22 13:36:21 raspberrypi java[2525]:         at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:68)
mar 22 13:36:21 raspberrypi java[2525]:         ... 10 more`

I'll post the full output if needed, thanks you for looking into this!

**Comment by devgianlu** [comment]
Please have a look at the audio configuration process: https://github.com/librespot-org/librespot-java#audio-output-configuration

**Comment by spocon** [comment]
Looks like you have four mixers. 

Copy one of them into config in /opt/spocon/config.toml in 'mixersearchkeyword'

2020-03-22 13:29:11 INFO LineHelper:61 - Available mixers: 'PulseAudio Mixer', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'ALSA [plughw:0,2]'

**Comment by arnib13** [comment]
Thank you both for the suggestions. I have now tried to put each of the mixers in the 'mixerSearchKeywords' and restarted after each modification. No luck after each, same error. Lastly I put all of them in separated by semicolon and no luck. Here is the most recent error: 

`mar 22 21:01:21 raspberrypi java[1073]: Exception in thread "zeroconf-client-30084423" xyz.gianlu.librespot.player.mixing.LineHelper$MixerException: No mixers available for the specified search keywords: ['PulseAudio Mixer', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'ALSA [plughw:0,2]']`

And here is how the config line looks: 

`mixerSearchKeywords = "'PulseAudio Mixer';'ALSA [plughw:0,0]';'ALSA [plughw:0,1]';'ALSA [plughw:0,2]'"`

**Comment by devgianlu** [comment]
You shouldn't include the single quotes, try with `0,0` or `0,1` etc..

**Comment by arnib13** [comment]
Sound is now working with the following line

`        mixerSearchKeywords = "ALSA"
`

Thank you for your help!

**Comment by skoeb** [comment]
Amazing package! Adding some info on the mixerSearchKeywords to the README would be helpful, the instructions in this thread got it working for me. In my case, I needed to add "Generic" to the mixerSearchKeywords.

**Comment by devgianlu** [comment]
> Amazing package! Adding some info on the mixerSearchKeywords to the README would be helpful, the instructions in this thread got it working for me. In my case, I needed to add "Generic" to the mixerSearchKeywords.

There are some instructions [here](https://github.com/librespot-org/librespot-java/tree/dev/player#audio-output-configuration).
