### ISSUE TITLE
Use api jar instead of core jar?

### ISSUE THREAD

**Issue by uvjustin** [spocon/spocon#13]
The api-jar-with-dependencies isn't much larger than the core-jar-with-dependencies (10.3 MB vs 7.5 MB as of the latest release) and it provides additional api functionality

**Comment by spocon** [comment]
hej uvjustin,
you are right , will be implemented in the next release

**Comment by JeremieRapin** [comment]
Hi, it will be really great to add it. 
Do you know when we can expect the next release?
Last but not least, thanks for your job.

**Comment by spocon** [comment]
Hej, The version numbers are connected to the librespot-java project. When a new release shows up i will add your request

**Comment by spocon** [comment]
Release 1.3.1 is using the api version from  fromhttps://github.com/librespot-org/librespot-java. Closing this
