### ISSUE TITLE
No Gapless playback

### ISSUE THREAD

**Issue by st0nec0ld** [spocon/spocon#16]
Hi, i made a fresh clean install with 2020-02-13-raspbian-buster-lite. There is always a little gap between to song, is there any way to activate gapless playback?

**Comment by devgianlu** [comment]
Gapless playback is enabled by default, the current version is affect by a small issue related to network connectivity. This will be sorted out in the next release.

**Comment by spocon** [comment]
New Release 1.3.1 is out. This should fix the issue. Please open a ticket in https://github.com/librespot-org/librespot-java if there are issues
