### ISSUE TITLE
Spocon hangs on connecting

### ISSUE THREAD

**Issue by XeOS1977** [spocon/spocon#17]
I've installed SpoCon on Debian Stretch through the 'easy' install. When I try to connect from a phone (Xperia 1) it keeps saying connecting and eventually does nothing. I've configged Spocon to connect to Snapcast server. I don't see any audio errors (I think).
I've also attached my config and output from journalctl --no-pager -f -u spocon. 

[config_toml.txt](https://github.com/spocon/spocon/files/4564289/config_toml.txt)
[journalctl_ouput_spocon.txt](https://github.com/spocon/spocon/files/4564290/journalctl_ouput_spocon.txt)

service spocon status:
● spocon.service - SpoCon
   Loaded: loaded (/lib/systemd/system/spocon.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-05-01 14:43:13 CEST; 18min ago
  Process: 24144 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
 Main PID: 24148 (java)
    Tasks: 61 (limit: 4915)
   Memory: 179.4M
      CPU: 15.598s
   CGroup: /system.slice/spocon.service
           └─24148 /usr/bin/java -jar /opt/spocon/librespot-java-api-v1.3.1.jar

May 01 15:01:18 thuisbasis java[24148]:         at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
May 01 15:01:18 thuisbasis java[24148]:         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
May 01 15:01:18 thuisbasis java[24148]:         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
May 01 15:01:18 thuisbasis java[24148]:         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
May 01 15:01:18 thuisbasis java[24148]:         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
May 01 15:01:18 thuisbasis java[24148]:         at java.base/java.net.Socket.connect(Socket.java:609)
May 01 15:01:18 thuisbasis java[24148]:         at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:117)
May 01 15:01:18 thuisbasis java[24148]:         at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:266)
May 01 15:01:18 thuisbasis java[24148]:         ... 24 more
May 01 15:01:18 thuisbasis java[24148]: 2020-05-01 15:01:18,110 [OkHttp https://guc-dealer.spotify.com/...] TRACE DealerClient:238 - Scheduled reconnection attempt in 10 seconds...

**Comment by devgianlu** [comment]
Could you try to ping `guc-dealer.spotify.com` from the machine? It looks like it doesn't have network connection.

**Comment by XeOS1977** [comment]
It is connected and it gives good ping on guc-dealer.spotify.com:
--- guc-dealer-ssl.spotify.com ping statistics ---
76 packets transmitted, 76 received, 0% packet loss, time 75120ms
rtt min/avg/max/mdev = 3.823/3.905/4.130/0.080 ms

**Comment by devgianlu** [comment]
Does it fail to connect every time?

**Comment by XeOS1977** [comment]
Yes, every time, url's from Spotify change as well

**Comment by spocon** [comment]
your config toml looks a little bit strange : you have all configs 2 times in that file ... was that a copy past issue or is it in your toml the same ?

**Comment by XeOS1977** [comment]
Oh, I'm sorry, that was a copy/paste error, there are no double entries in the actual config.toml

**Comment by spocon** [comment]
@XeOS1977 
a new version is out , please try if your issue is fixed

**Comment by spocon** [comment]
closing
