### ISSUE TITLE
Device never connects

### ISSUE THREAD

**Issue by martinktech** [spocon/spocon#19]
The Pi is connecting to the spotify server● spocon.service - SpoCon
   Loaded: loaded (/lib/systemd/system/spocon.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-07-13 17:49:03 BST; 2h 29min ago
  Process: 12622 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
 Main PID: 12624 (java)
   Memory: 59.3M
   CGroup: /system.slice/spocon.service
           └─12624 /usr/bin/java -jar /opt/spocon/librespot-java-api-v1.4.0.jar

Jul 13 20:15:23 raspberrypi java[12624]: 2020-07-13 20:15:23,464 INFO  ZeroconfServer:280 - y0595*****************rk is already trying to connect.
Jul 13 20:15:23 raspberrypi java[12624]: 2020-07-13 20:15:23,589 TRACE ZeroconfServer:477 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66
Jul 13 20:16:07 raspberrypi java[12624]: 2020-07-13 20:16:07,572 TRACE ZeroconfServer:477 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66 Android/29 (ON
Jul 13 20:16:51 raspberrypi java[12624]: 2020-07-13 20:16:51,765 TRACE ZeroconfServer:477 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66
Jul 13 20:16:55 raspberrypi java[12624]: 2020-07-13 20:16:55,346 TRACE ZeroconfServer:477 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66
Jul 13 20:17:08 raspberrypi java[12624]: 2020-07-13 20:17:08,399 TRACE ZeroconfServer:477 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66 Android/29 (ONEPLUS A6003),
Jul 13 20:17:08 raspberrypi java[12624]: 2020-07-13 20:17:08,412 INFO  ZeroconfServer:280 - y0595********************6rk is already trying to connect.
Jul 13 20:17:08 raspberrypi java[12624]: 2020-07-13 20:17:08,465 TRACE ZeroconfServer:477 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66
Jul 13 20:17:10 raspberrypi java[12624]: 2020-07-13 20:17:10,504 TRACE ZeroconfServer:477 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.66 Android/29 (ONEPLUS A6003),
Jul 13 20:17:10 raspberrypi java[12624]: 2020-07-13 20:17:10,515 INFO  ZeroconfServer:280 - y0595****************6rk is already trying to connect.
lines 1-19/19 (END)

**Comment by devgianlu** [comment]
Does this happen on the first try? Also, are you able to connect manually with the credentials?

**Comment by spocon** [comment]
closing cause of inactivity
