### ISSUE TITLE
Soundcard not detected

### ISSUE THREAD

**Issue by jan-koch** [spocon/spocon#2]
I am coming to SpoCon because Raspotify did not produce clear sound with my soundcard (X-Fi).

SpoCon does not output sound at all, how do I need to configure the external soundcard in the settings? The card itself is working, I can hear music when using Mopidy (but that doesn't support Spotify Connect AFAIK).

Thanks,
Jan

**Comment by spocon** [comment]
Hi Jan-Koch,
thanks for your bug report. Could you try to restart the service ? 
open a terminal :
```
sudo service spocon restart
```
For output : 
```
sudo journalctl -u spocon
```
If that couldn't help i would recommend to open an bug report for the developers: [librespot-java project issues ](https://github.com/librespot-org/librespot-java/issues)

**Comment by spocon** [comment]
maybe that helps you as well : https://github.com/librespot-org/librespot-java/issues/53

**Comment by jan-koch** [comment]
`-- Logs begin at Thu 2019-02-14 11:11:59 CET, end at Mon 2019-07-22 07:51:26 CEST. --
Jul 21 15:48:35 raspberrypi systemd[1]: Starting SpoCon...
Jul 21 15:48:36 raspberrypi sh[474]: ping: spotify.com: Temporärer Fehler bei der Namensauflösung
Jul 21 15:48:41 raspberrypi sh[474]: ping: spotify.com: Temporärer Fehler bei der Namensauflösung
Jul 21 15:48:46 raspberrypi sh[474]: ping: spotify.com: Temporärer Fehler bei der Namensauflösung
Jul 21 15:48:51 raspberrypi sh[474]: PING spotify.com (104.154.127.47) 56(84) bytes of data.
Jul 21 15:48:51 raspberrypi sh[474]: 64 bytes from 47.127.154.104.bc.googleusercontent.com (104.154.127.47): icmp_seq=1 ttl=40 time=143 ms
Jul 21 15:48:51 raspberrypi sh[474]: --- spotify.com ping statistics ---
Jul 21 15:48:51 raspberrypi sh[474]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jul 21 15:48:51 raspberrypi sh[474]: rtt min/avg/max/mdev = 142.877/142.877/142.877/0.000 ms
Jul 21 15:48:51 raspberrypi systemd[1]: Started SpoCon.
Jul 21 15:48:56 raspberrypi java[1088]: 2019-07-21 15:48:56 INFO  Session:98 - Created new session! {deviceId: 28bea14c-eee7-409a-b5fa-7fcdac474075, ap: gew1-accesspoint-a-14zn.ap.spotify.com/104.199.64.207}
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:242 - Connected successfully!
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 DEBUG TimeProvider:20 - Corrected time offset, delta: 9s
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 TRACE Session:741 - Handled Ping {payload: 5D346D53}
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:778 - Skipping SecretBlock
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:758 - Received LicenseVersion: 1, 1.0.0-DE
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:751 - Received CountryCode: DE
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:778 - Skipping ProductInfo
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:778 - Skipping LegacyWelcome
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:778 - Skipping UnknownData_AllZeros
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 DEBUG Session:761 - Received 0x10: C668A146063486B5B3522E96922EF16B7B1983E8
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 TRACE Session:747 - Handled PongAck {payload: 5D346D53}
Jul 21 15:48:58 raspberrypi java[1088]: 2019-07-21 15:48:58 INFO  Session:723 - Skipping unknown command {cmd: 0x75, payload: 000000}
Jul 21 15:49:01 raspberrypi java[1088]: 2019-07-21 15:49:01 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeHello
Jul 21 15:49:01 raspberrypi java[1088]: 2019-07-21 15:49:01 TRACE MercuryClient:131 - Send Mercury request, seq: 1, uri: hm://remote/3/user/jan_koch/, method: POST
Jul 21 15:49:01 raspberrypi java[1088]: 2019-07-21 15:49:01 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 1
Jul 21 15:49:01 raspberrypi java[1088]: 2019-07-21 15:49:01 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeHello
Jul 21 15:49:02 raspberrypi java[1088]: 2019-07-21 15:49:02 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: -3549113583298150400, flags: 1, parts: 2
Jul 21 15:49:02 raspberrypi java[1088]: 2019-07-21 15:49:02 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: -3477055989260222464, flags: 1, parts: 2
Jul 21 15:49:02 raspberrypi java[1088]: 2019-07-21 15:49:02 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeNotify, ident: 737aea68b93eb137c354f2e3f8712395de480c4f
Jul 21 15:49:02 raspberrypi java[1088]: 2019-07-21 15:49:02 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeNotify, ident: 34549626d56ac86d0c89dd96d1a743979dbfe12c
Jul 21 15:49:02 raspberrypi java[1088]: 2019-07-21 15:49:02 INFO  Session:258 - Authenticated as jan_koch!
Jul 21 15:50:03 raspberrypi java[1088]: 2019-07-21 15:50:03 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: 3440754513357570048, flags: 1, parts: 2
Jul 21 15:50:03 raspberrypi java[1088]: 2019-07-21 15:50:03 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeNotify, ident: 34549626d56ac86d0c89dd96d1a743979dbfe12c
Jul 21 15:50:05 raspberrypi java[1088]: 2019-07-21 15:50:05 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: 3801042483547209728, flags: 1, parts: 2
Jul 21 15:50:05 raspberrypi java[1088]: 2019-07-21 15:50:05 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeLoad, ident: 34549626d56ac86d0c89dd96d1a743979dbfe12c
Jul 21 15:50:05 raspberrypi java[1088]: 2019-07-21 15:50:05 TRACE Player:187 - Frame has context_player_state: {"endpoint":"play","context":{"uri":"spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy","metadat
Jul 21 15:50:05 raspberrypi java[1088]: 2019-07-21 15:50:05 DEBUG Player:363 - Loading context, uri: spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE MercuryClient:131 - Send Mercury request, seq: 2, uri: hm://remote/3/user/jan_koch/, method: POST
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 2, flags: 1, parts: 1
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE MercuryClient:131 - Send Mercury request, seq: 3, uri: hm://remote/3/user/jan_koch/, method: POST
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 3, flags: 1, parts: 1
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE MercuryClient:131 - Send Mercury request, seq: 4, uri: hm://metadata/4/track/7d4b2c1bf30440bfa47e769fb17b02d8, method: GET
Jul 21 15:50:06 raspberrypi java[1088]: 2019-07-21 15:50:06 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 4, flags: 1, parts: 2
Jul 21 15:50:07 raspberrypi java[1088]: 2019-07-21 15:50:07 DEBUG TokenProvider:47 - Token expired or not suitable, requesting again. {scope: playlist-read, token: null}
Jul 21 15:50:07 raspberrypi java[1088]: 2019-07-21 15:50:07 TRACE MercuryClient:131 - Send Mercury request, seq: 5, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a0772
Jul 21 15:50:07 raspberrypi java[1088]: 2019-07-21 15:50:07 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 5, flags: 1, parts: 2
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: 4521618423926489088, flags: 1, parts: 2
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeLoad, ident: 34549626d56ac86d0c89dd96d1a743979dbfe12c
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE Player:187 - Frame has context_player_state: {"endpoint":"play","context":{"uri":"spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy","metadat
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 DEBUG Player:363 - Loading context, uri: spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:131 - Send Mercury request, seq: 6, uri: hm://context-resolve/v1/spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy, method: GET
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:131 - Send Mercury request, seq: 7, uri: hm://remote/3/user/jan_koch/, method: POST
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 6, flags: 0, parts: 1
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 6, flags: 2, parts: 1
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 6, flags: 2, parts: 1
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 7, flags: 1, parts: 1
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 6, flags: 1, parts: 1
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:131 - Send Mercury request, seq: 8, uri: hm://remote/3/user/jan_koch/, method: POST
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 8, flags: 1, parts: 1
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:131 - Send Mercury request, seq: 9, uri: hm://metadata/4/track/7d4b2c1bf30440bfa47e769fb17b02d8, method: GET
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 9, flags: 1, parts: 2
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 DEBUG CdnManager:97 - Fetched CDN url for BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611: http://audio4-fa.scdn.co/audio/bd6ec3bebbef65299b6e28abdfe46cc2e6e
Jul 21 15:50:09 raspberrypi java[1088]: 2019-07-21 15:50:09 TRACE CdnManager:274 - Chunk 0/27 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611}
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 DEBUG CdnManager:97 - Fetched CDN url for BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611: http://audio4-ak.spotify.com.edgesuite.net/audio/bd6ec3bebbef65299
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 0/27 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 0/27 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611}
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 0/27 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 1/27 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 1/27 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611}
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 2/27 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611}
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 2/27 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 3/27 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611}
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE NormalizationData:29 - Loaded normalization data, track_gain: -10,09, track_peak: 1,23, album_gain: -10,09, album_peak: 1,23
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE NormalizationData:29 - Loaded normalization data, track_gain: -10,09, track_peak: 1,23, album_gain: -10,09, album_peak: 1,23
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 TRACE CdnManager:274 - Chunk 3/27 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: true, stream: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2
Jul 21 15:50:10 raspberrypi java[1088]: 2019-07-21 15:50:10 INFO  TrackHandler:80 - Loaded track, name: 'King Of My Castle - Don Diablo Edit', artists: 'Don Diablo, Keanu Silva', gid: 7D4B2C1BF30440BFA47E769FB1
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: 4881906394116128768, flags: 1, parts: 2
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 INFO  LinesHolder:65 - Available mixers: 'Pro [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'Pro [plughw:1,0]', 'Pro [plughw:1,1]'
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeLoad, ident: 34549626d56ac86d0c89dd96d1a743979dbfe12c
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE Player:187 - Frame has context_player_state: {"endpoint":"play","context":{"uri":"spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy","metadat
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE PlayerRunner:36 - Player ready for playback, codec: VORBIS, fileId: {fileId: BD6EC3BEBBEF65299B6E28ABDFE46CC2E6EA7611}
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 DEBUG Player:363 - Loading context, uri: spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:131 - Send Mercury request, seq: 10, uri: hm://context-resolve/v1/spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy, method: GE
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:131 - Send Mercury request, seq: 11, uri: hm://remote/3/user/jan_koch/, method: POST
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 0, parts: 1
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 1, parts: 1
Jul 21 15:50:11 raspberrypi java[1088]: 2019-07-21 15:50:11 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
Jul 21 15:50:11 raspberrypi java[1088]: Exception in thread "handle-packet-23944394" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept
Jul 21 15:50:11 raspberrypi java[1088]:         at com.google.gson.JsonParser.parse(JsonParser.java:65)
Jul 21 15:50:11 raspberrypi java[1088]:         at xyz.gianlu.librespot.mercury.JsonMercuryRequest.instantiate(JsonMercuryRequest.java:27)
lines 1-102`

Sorry for the delay, that is the output of 
`sudo journalctl -u spocon`

**Comment by jan-koch** [comment]
There's a Java exception:
`Jul 21 15:50:11 raspberrypi java[1088]: Exception in thread "handle-packet-23944394" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept
Jul 21 15:50:11 raspberrypi java[1088]:         at com.google.gson.JsonParser.parse(JsonParser.java:65)
Jul 21 15:50:11 raspberrypi java[1088]:         at xyz.gianlu.librespot.mercury.JsonMercuryRequest.instantiate(JsonMercuryRequest.java:27`

**Comment by spocon** [comment]
That means that it could not read your config.toml in /opt/spocon/config.toml.

Try this :

```
sudo apt install dos2unix 
sudo dos2unix /opt/spocon/config.toml
sudo service spocon restart
```
btw which version are you using ?
```
sudo apt list spocon
```

**Comment by jan-koch** [comment]
Thanks for the quick response, will test that!
Version info:
`spocon/bionic,now 0.16.4 armhf`

**Comment by devgianlu** [comment]
There seems to be an issue with librespot-java, for some reason it is receiving a truncated JSON message:

> 2019-07-21 15:50:11 TRACE Player:187 - Frame has context_player_state: {"endpoint":"play","context":{"uri":"spotify:user:spotify:playlist:37i9dQZF1DWUq3wF0JVtEy","metadat

Does this happen consistently?

**Comment by jan-koch** [comment]
I'm sorry, that was my bad in copying the log message. The JSON is not truncated, but copying from my Windows Bash only copied the visible characters

**Comment by devgianlu** [comment]
Could you post the full JSON?

**Comment by jan-koch** [comment]
Here's the full output from `sudo journalctl -u spocon` as a log file. 
[spocon.log](https://github.com/spocon/spocon/files/3416276/spocon.log)

**Comment by devgianlu** [comment]
I suppose your "favorite songs" playlist is very big. Anyway, there seems to be an issue with receiving the response from the server. 

```
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 0, parts: 1
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 1, parts: 1
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
```
should be
```
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 0, parts: 1
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 2, parts: 1
MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 10, flags: 1, parts: 1
```

I don't know what's wrong here, but this system is not used anymore in the newest version (yet to be released). Are you able to compile from source? Or maybe we can ask @spocon to create a dev build of the `new-spotify-api` branch?

**Comment by spocon** [comment]
sure , no problem. give me 30 min

**Comment by jan-koch** [comment]
I appreciate your efforts in helping me, fantastic service!

**Comment by jan-koch** [comment]
@devgianlu the playlists I listen to usually have anywhere from 15 - 200+ songs, in case that info helps

**Comment by spocon** [comment]
@jan-koch 30 min was a bit to optimistic. But it will be released today. There are some things which have to be fixed first.

**Comment by jan-koch** [comment]
No worries, thank you for the effort!

**Comment by spocon** [comment]
Hej Jan,

I have build the package but launchpad ppa ( the repository which holds our packages.) is today very slow with publishing the packages. 

You can check the status here: 
https://launchpad.net/~spocon/+archive/ubuntu/spocon/+packages

Once thats done and status is published you can just do a:
```
sudo apt update & sudo apt upgrade
```

**Comment by spocon** [comment]
ok its done :-)

**Comment by spocon** [comment]
one more thing:
@devgianlu 
I tested the new-spotify-api and the first time when i installed it it couldn't find the mixer. Had to restart the service

I wrote a bug report for it:

https://github.com/librespot-org/librespot-java/issues/117

**Comment by jan-koch** [comment]
Than you @spocon! Will test it out today and keep you posted

**Comment by spocon** [comment]
Unfortunately the new version has some bugs. 

When connecting to spocon and than go back to my former device spocon continues to play. Reconning to spocon is not possible and I'm ending up to here music on two devices 
@devgianlu 
I'm on my way to the airport. But will create a bug report this evening.

**Comment by jan-koch** [comment]
Yeah, was just about to say that I also see Java exceptions with the new version. Attached the output of `sudo journalctl -u spocon`.
[spocon.log](https://github.com/spocon/spocon/files/3420371/spocon.log)

**Comment by devgianlu** [comment]
The latest commits on `new-spotify-api` should fix these issues.

**Comment by jan-koch** [comment]
Thanks, @devgianlu.
What's the best way for me to test? Compile `new-spotify-api` from source?

**Comment by devgianlu** [comment]
Definitely, it is quite simple and recompiling is very inexpensive.

**Comment by jan-koch** [comment]
Ok, will see if I can manage to do that successfully :-D

**Comment by jan-koch** [comment]
Managed to recompile and librespot-java is showing up as device in Spotify under connected devices. But it does not output sound, restarting the Raspberry Pi didn't help.

Not sure if I configured librespot-java to grab the USB soundcard properly though. Sorry, I'm not an expert at this stuff, just learning

**Comment by spocon** [comment]
did you try this as well ? 
https://github.com/spocon/spocon#troubleshooting

btw. i have made new version , it fixes the most of the issues with librespot-java ( at least with HDMI output on TV) 
```
sudo apt update & sudo apt upgrade
```

fixed as well : 
- An issue with gpg-key from the keyserver ubuntu ( was not importing correctly)
- Audio permission , one time bug with installation 

 now the installation should be smooth

**Comment by jan-koch** [comment]
Yes, I have updated alsa.cnf and created the snd_soc_core.cnf file.
I also updated via apt, but got another Java exception, please see the logfile attached.
[spocon.log](https://github.com/spocon/spocon/files/3425860/spocon.log)

**Comment by spocon** [comment]
The changes in troubleshotting are for alsa but you are using "Pro" as default [ which will be picked]
```
Available mixers: 'Pro [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'Pro [plughw:1,0]', 'Pro [plughw:1,1]'
```
try this:
go to /opt/spocon/config.toml

replace 
```
mixerSearchKeywords = ""
```
with
``` 
mixerSearchKeywords = "ALSA"
```
and
```
sudo service spocon restart
```

**Comment by devgianlu** [comment]
I've added a small guide to the README: https://github.com/librespot-org/librespot-java/blob/master/README.md#audio-output-configuration

**Comment by jan-koch** [comment]
Getting closer!
I see these infos when running the newly compiled `new-spotify-api` from librespot-java:
```
2019-07-24 17:28:06 INFO  LinesHolder:65 - Available mixers: 'ALSA [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'Pro [plughw:1,0]', 'Pro [plughw:1,1]'
2019-07-24 17:28:06 TRACE PlayerRunner:36 - Player ready for playback, codec: VORBIS, fileId: {fileId: 568C74AC29940FA9E68C86F64E8D17907B4ED34C}
2019-07-24 17:28:06 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
2019-07-24 17:28:06 TRACE MercuryClient:131 - Send Mercury request, seq: 7, uri: hm://remote/3/user/jan_koch/, method: POST
2019-07-24 17:28:06 TRACE LinesHolder:142 - New line opened for mixer 'ALSA [default]'.
```

I have set config.toml in the librespot-java folder to:
```
mixerSearchKeywords = "Pro [plughw:1,1]"
```

Given that's the correct identifier of the soundcard, is that the correct syntax? I do not see exceptions anymore but no sound either.

**Comment by devgianlu** [comment]
Try updating to the latest commit, I had to change the divider from `,` to `;`.

**Comment by jan-koch** [comment]
It's working!!! 
Running librespot-java directly now, with the ´new-spotify-api` build.

THANK YOU! You've made my entire week :)

**Comment by spocon** [comment]
will create a new version for this

**Comment by devgianlu** [comment]
@jan-koch Awesome! Since you're running `new-spotify-api`, you can report any issue on librespot-org/librespot-java#105

**Comment by jan-koch** [comment]
Will do if I encounter any!
