### ISSUE TITLE
SpoCon 1.4.0 package not available in Ubuntu 20.04 LTS repository

### ISSUE THREAD

**Issue by Phontana** [spocon/spocon#20]
**Describe the bug**
See title. The latest release of SpoCon is not available for Ubuntu 20.04 LTS, 1.3.1 is downloaded instead. 

**To Reproduce**
1. Add SpoCon repository on a 20.04 LTS system
2. Install SpoCon by following the installation instructions

**Expected behavior**
1.4.0 can be downloaded for 20.04 systems as well.

**Comment by spocon** [comment]
done, please close when you installed the new version

**Comment by Phontana** [comment]
Thanks, I just installed it.
