### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by DenisMtfl** [spocon/spocon#25]
i trying to connect with my iPhone to my RaspberryPi 4 and no Connection ... only waiting. Here is the log.
**So raspotify is much easier to handle! Why?**

-- Logs begin at Thu 2021-01-28 20:17:02 CET. --
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.core.Session$Builder.decryptBlob(Session.java:879) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.core.Session$Builder.blob(Session.java:970) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer.handleAddUser(ZeroconfServer.java:349) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer.access$200(ZeroconfServer.java:40) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:482) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:557) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:465) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:20 berry4 java[31513]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
Jan 29 10:01:20 berry4 java[31513]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
Jan 29 10:01:20 berry4 java[31513]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]: 2021-01-29 10:01:43,338 TRACE ZeroconfServer:519 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.96 iOS/14.4 (iPhone10,4), Host=192.168.1.210, Accept-Encoding=gzip, Content-Length=702, Content-Type=application/x-www-form-urlencoded}
Jan 29 10:01:43 berry4 java[31513]: 2021-01-29 10:01:43,356 INFO  ZeroconfServer:328 - Accepted new user from iPhone von Denis. {deviceId: 6779cefe4a4ec0c18fd082ea65e153aa880c745c}
Jan 29 10:01:43 berry4 java[31513]: 2021-01-29 10:01:43,364 FATAL ZeroconfServer:358 - Couldn't establish a new session.
Jan 29 10:01:43 berry4 java[31513]: java.security.InvalidKeyException: Illegal key size or default parameters
Jan 29 10:01:43 berry4 java[31513]:         at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026) ~[?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at javax.crypto.Cipher.implInit(Cipher.java:801) ~[?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at javax.crypto.Cipher.chooseProvider(Cipher.java:864) ~[?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at javax.crypto.Cipher.init(Cipher.java:1249) ~[?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at javax.crypto.Cipher.init(Cipher.java:1186) ~[?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.core.Session$Builder.decryptBlob(Session.java:879) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.core.Session$Builder.blob(Session.java:970) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer.handleAddUser(ZeroconfServer.java:349) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer.access$200(ZeroconfServer.java:40) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:482) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:557) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:465) ~[librespot-java-api-v1.5.4.jar:1.5.4]
Jan 29 10:01:43 berry4 java[31513]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
Jan 29 10:01:43 berry4 java[31513]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by devgianlu** [comment]
It might be an issue with your JCE. Try this: https://stackoverflow.com/a/6481658/5446197

**Comment by DenisMtfl** [comment]
> It might be an issue with your JCE. Try this: https://stackoverflow.com/a/6481658/5446197

Yeah i have updated java to OpenJDK Java 11 and _sudo update-alternatives --config java_ to this version.
And now its working. Before it was _/usr/lib/jvm/zulu-embedded-8-armhf/bin/java_. What the hell !?

But is it a Bug? Can you check the java version on apt install ?

**Comment by devgianlu** [comment]
I don't think this a bug with librespot-java or spocon either. @spocon might know something more about this.

**Comment by spocon** [comment]
i never heard of this problem , maybe a config problem of the system . Im closing this until there is another similer problem coming up
