### ISSUE TITLE
Key Failure

### ISSUE THREAD

**Issue by jshep321** [spocon/spocon#28]
Hi,
Trying to install on raspbian and keyserver failure.  The curl | sh fails, so attempted manually also:

Manual attempt:
```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7DBE8BF06EA39B78

Executing: /tmp/apt-key-gpghome.4wBPyQbP7K/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7DBE8BF06EA39B78
gpg: keyserver receive failed: Server indicated a failure

```

Outdated key perhaps?

Thanks!

**Comment by spocon** [comment]
Not a bug , seems like a server issue:

https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure

**Comment by jshep321** [comment]
Yep, you're right.... rookie mistake.  I'm using my DHCP server (router) to setup the DNS.  Every other service works fine except this.

Added  ```nameserver 1.1.1.1``` to /etc/resolv.conf and it installs.  Odd.

Thanks!
