### ISSUE TITLE
Unmet dependency for openjdk-11-jre on Picroft

### ISSUE THREAD

**Issue by mashers** [spocon/spocon#3]
When installing using install.sh on the Picroft distribution (Raspbian with Mycroft AI preinstalled), the following error is encountered:

spocon : Depends: openjdk-11-jre but it is not installable

**To Reproduce**
1. Write the Picroft distribution to SD card
2. Boot RPi to Picroft, and when the setup script launches press CTRL-C to get to bash prompt
3. Run the spocon installer

**Expected behavior**
Spocon should be installed

**Comment by spocon** [comment]
Have you tried "sudo apt install openjdk-11-jre" ? Which version are you running ? Buster ?🤔

**Comment by mashers** [comment]
Thanks for the quick reply! Here's what I get when I try to use apt:

> Package openjdk-11-jre is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'openjdk-11-jre' has no installation candidate

I also tried to download a deb and install that and got errors about an incompatible version of libc (and some other things).

Here's output from uname -a:

>Linux mycroft 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux

Picroft is built on Raspbian Stretch, which I realise is a couple of years old. Could that be related to the problem?

**Comment by mashers** [comment]
I'm just trying an in-place upgrade to Buster now...

**Comment by spocon** [comment]
Good idea . Otherwise stretch version has has openjdk 11 in the backports

http://markjatboinc.blogspot.com/2017/09/add-stretch-backports-to-rpi.html?m=1

But probably a better idea to upgrade ..

Den tis 6 aug. 2019 18:45mashers <notifications@github.com> skrev:

**Comment by mashers** [comment]
Oh nice, I forgot about backports. Thanks! dist-upgrade is still running, and I'm hoping there isn't a reason why it's running on Stretch rather than Buster 0_o

**Comment by spocon** [comment]
No worries , I have it running on a raspbian buster ;)

**Comment by mashers** [comment]
Well, sadly it didn't work after upgrading from Stretch to Buster. It installed all the dependencies fine, so I don't think this is an issue with spocon, but rather that I mangled it while trying to get it working :p I'm about to re-flash the Stretch-based Picroft distro and then I'll try installing openjdk from backports. In any case, I'll close this bug report. Thanks so much for your guidance :)
