### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by cooltrooper** [spocon/spocon#30]
Hello,

Is it possible to add the REST API configuration to this software?
I believe librespot-java has this nativly?

Thanks, great project!

**Comment by devgianlu** [comment]
I believe it's already using the API variant.

**Comment by cooltrooper** [comment]
Brill, on my instance i cant seem to access it? Perhaps I'm missing something obvious!

**Comment by spocon** [comment]
latest version of spocon is using librespot-java-api-v{{ librespot_version }}.jar which has api included. please check if you have the latest version installed
