### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by mrxflight** [spocon/spocon#31]
**Is your feature request related to a problem? Please describe.**
My Problem is that I can't control my Spocon client threw the spotify Web API after a specific time of roundabout 10 h. After this time I think the client goes into "sleep mode" and is not accessible threw the API anymore.

**Describe the solution you'd like**
It would be nice if there would be an option that disables the sleep mode entirely or if there would be a function that disables it.

**Comment by devgianlu** [comment]
There is no sleep mode in the client. What do you mean it is not accessible from the API? Do you see any error in the logs?

**Comment by mrxflight** [comment]
Hi,
so if I start the client I can play musik threw it from the spotify application. After I play musik it also appears on the device list from the Web Api and I can control it threw my python code. But after these 10 h it does not appear in the device list anymore. I read in the Spotify Web docs that one possible cause is that the device has a sleep mode. Here is the link: https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/

Do you know any possible solutions for this? I run the client on my raspberry pi and want to use it as a morning clock.

**Comment by devgianlu** [comment]
Can you attach the spocon logs around the time it stops showing up?

**Comment by mrxflight** [comment]
[spocon Mar 25 - Mar 26.log](https://github.com/spocon/spocon/files/6221706/spocon.Mar.25.-.Mar.26.log)
Here is the log file from Mar 24 - 26. It should have been accessible on Mar 25 06:43 and Mar 26 06:43 (That's the time I set up the clock). In this logs it did not work.
[spocon Mar 28 - Mar 29.log](https://github.com/spocon/spocon/files/6221728/spocon.Mar.28.-.Mar.29.log)
This is one example from today were it worked.

By the way Thank you for your quick answers.

**Comment by devgianlu** [comment]
Looks like the usual reconnection issue librespot-java has.
