### ISSUE TITLE
Works Like a Charm, BUT...

### ISSUE THREAD

**Issue by j415howard** [spocon/spocon#33]
Not sure how to use with NordVPN which seems to terminate or block SpoCon.  Firewall (not the same thing as VPN) instructions say open the UDP port 5355 for mDNS. Then specify some random port in zeroconf.listenPort and open that TCP port too.  I see no reference to UDP in config.toml.  Only API port = 24879.

Also, zeroconf ListenPort = -1 in config.toml.  Should I change that?  If so, to what?

Also, currently, initialVolume = 65536.  My (iOS) Spotify app is at 100% volume when connected to SpoCon.  Will cutting initialVolume in half cut my Spotify app in half?

**Comment by Gandalf1783** [comment]
I cant get it to work.
FYI: Its port 5353, at least thats what im seeing with "sudo netstat -pnltu | grep 5353".
Thats the usual Port mDNS services run on.

However, it doesnt seem to work with Windows. Any ideas?

**Comment by devgianlu** [comment]
You also need to hardcode a random port for `zeroconf.listenPort` and open that TCP port for Spotify Connect to work.

> Will cutting initialVolume in half cut my Spotify app in half?

Yes, they are synced.

**Comment by Gandalf1783** [comment]
Well i have overread that i need Spotify Premium, so i guess i wont use it :)
Thanks anyways :)

**Comment by spocon** [comment]
closing
