### ISSUE TITLE
Armel support request

### ISSUE THREAD

**Issue by cdlenfert** [spocon/spocon#35]
I have a music server running on armv6l device (and another on armv5tel). I've run librespot successfully on the armv6l device before, however there were connection issues happening at random (and not due to resources) and I ultimately couldn't use it. I'd like to give Spocon a try on these devices but I'm not familiar with how I might go about building for these architectures. Thanks in advance if anyone can point me in the right direction.

**Comment by spocon** [comment]
He cdlenfert, 

we are using ubuntus launchpad to compile the deb package to various devices . Currently we are only supporting these variants:

![bild](https://user-images.githubusercontent.com/52956690/123508544-5c690600-d670-11eb-80e8-ee97a4618780.png)


you can download them directly here : 

https://launchpad.net/~spocon/+archive/ubuntu/spocon/+packages

**Comment by cdlenfert** [comment]
Thank you for confirming.
