### ISSUE TITLE
Spotify connect incorrect time

### ISSUE THREAD

**Issue by michaelosten** [spocon/spocon#36]
librespot-java-api-v1.6.0.jar

I'm using Spotify 8.6.30.968 (iphone) to control spocon (librespot-java-api-v1.6.0.jar) on Ubuntu 20.04.

Track progress time when paused continues to increase.  I resume playback, the iphone app returns to the correct time position.  If I leave it paused beyond the track length, the progress time is blank.

This is only from within the iphone app.  The spotify lockscreen widget pauses progress bar/time correctly.

NTP time sync is enabled on the host.

**Comment by spocon** [comment]
is this fixed with 1.6.1 ?

**Comment by devgianlu** [comment]
Nope

**Comment by spocon** [comment]
closing this
