### ISSUE TITLE
Song endings are being truncated

### ISSUE THREAD

**Issue by jshep321** [spocon/spocon#38]
**Describe the bug**
Song endings are being truncated

**To Reproduce**
I'm simply playing playlists and the tracks are ending prematurely  Unclear of exact timing, but seems to be ~4-6s.  I'm piping to forked-daapd (via a mkfifo pipe).

I can see the metadata track time/total time in forked-daapd webpage.  When this occurs, there is time remaining and it transitions to the next track.  I can also see the log file excerpt below while still playing.

The DEBUG logfiles show a Changed fade out reason why: TRACK_DONE

**Expected behavior**
Tracks should play to completion when being piped, else handle output delays correctly.

**Screenshots**
N/A 

**Logs**

**Desktop (please complete the following information):**
RPI4, 4GB

**Additional context**
I tried disabling preload and it didn't help. 

Perhaps adjusting the crossFadeDuration to 4-5s would correct this?  

I suspect disabling the fade out "TRACK_DONE" when sending to a pipe (or creating a new config option for this) would correct.  

Another info piece: there is a Player time offset of <1000.  It seems this doesn't take into account the forked-daapd synchronization delays.  Maybe it is only looking at the spocon -> forked-daapd delay?

**Comment by devgianlu** [comment]
Already fixed upstream: https://github.com/librespot-org/librespot-java/issues/361

**Comment by jshep321** [comment]
Hi @devgianlu 
I've never played with Ansible and lack the time to setup the build env now.  Is there a prebuilt armhf (RPI4) .jar anywhere until this trickles upstream into the repo? 
Thanks!

**Comment by devgianlu** [comment]
You can get the latest snapshots from: https://oss.sonatype.org/content/repositories/snapshots/xyz/gianlu/librespot/librespot-api/1.6.1-SNAPSHOT/

**Comment by jshep321** [comment]
> 
> 
> You can get the latest snapshots from: https://oss.sonatype.org/content/repositories/snapshots/xyz/gianlu/librespot/librespot-api/1.6.1-SNAPSHOT/

Thanks!
