### ISSUE TITLE
device not showing

### ISSUE THREAD

**Issue by tonygils** [spocon/spocon#39]
Hi,

I have tried to install it on different devices and OS, but i can't select the device on spotify.
Installed on a server and on a raspberry pi 3 & pi 4, on debian, raspbian and ubuntu. 

this is from the install:
`pi@raspberrypi:~ $ curl -sL https://spocon.github.io/spocon/install.sh | sh
Executing: /tmp/apt-key-gpghome.k0YbEze8Hz/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7DBE8BF06EA39B78
gpg: key 7DBE8BF06EA39B78: public key "Launchpad PPA for Thorsten Haga" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb http://ppa.launchpad.net/spocon/spocon/ubuntu bionic main
Get:1 http://ppa.launchpad.net/spocon/spocon/ubuntu bionic InRelease [15.9 kB]
Hit:2 http://archive.raspberrypi.org/debian buster InRelease               
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease            
Get:4 http://ppa.launchpad.net/spocon/spocon/ubuntu bionic/main armhf Packages [484 B]
Get:5 http://ppa.launchpad.net/spocon/spocon/ubuntu bionic/main Translation-en [208 B]
Fetched 16.6 kB in 3s (6,486 B/s)                             
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  python-colorzero
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  ca-certificates-java fonts-dejavu-extra java-common libatk-wrapper-java
  libatk-wrapper-java-jni openjdk-11-jre openjdk-11-jre-headless
Suggested packages:
  default-jre fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  ca-certificates-java fonts-dejavu-extra java-common libatk-wrapper-java
  libatk-wrapper-java-jni openjdk-11-jre openjdk-11-jre-headless spocon
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 47.5 MB of archives.
After this operation, 168 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/spocon/spocon/ubuntu bionic/main armhf spocon armhf 1.6.0 [12.6 MB]
Get:2 http://mirror.serverius.net/raspbian/raspbian buster/main armhf java-common all 0.71 [14.4 kB]
Get:3 http://mirror.serverius.net/raspbian/raspbian buster/main armhf openjdk-11-jre-headless armhf 11.0.11+9-1~deb10u1 [32.7 MB]
Get:5 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf fonts-dejavu-extra all 2.37-1 [1,982 kB]
Get:7 http://mirror.transip.net/raspbian/raspbian buster/main armhf libatk-wrapper-java-jni armhf 0.33.3-22 [33.7 kB]
Get:4 http://mirror.serverius.net/raspbian/raspbian buster/main armhf ca-certificates-java all 20190405 [15.7 kB]
Get:6 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libatk-wrapper-java all 0.33.3-22 [45.3 kB]
Get:8 http://mirror.serverius.net/raspbian/raspbian buster/main armhf openjdk-11-jre armhf 11.0.11+9-1~deb10u1 [148 kB]
Fetched 47.5 MB in 17s (2,721 kB/s)                                            
Selecting previously unselected package java-common.
(Reading database ... 98813 files and directories currently installed.)
Preparing to unpack .../0-java-common_0.71_all.deb ...
Unpacking java-common (0.71) ...
Selecting previously unselected package openjdk-11-jre-headless:armhf.
Preparing to unpack .../1-openjdk-11-jre-headless_11.0.11+9-1~deb10u1_armhf.deb ...
Unpacking openjdk-11-jre-headless:armhf (11.0.11+9-1~deb10u1) ...
Selecting previously unselected package ca-certificates-java.
Preparing to unpack .../2-ca-certificates-java_20190405_all.deb ...
Unpacking ca-certificates-java (20190405) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../3-fonts-dejavu-extra_2.37-1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-1) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../4-libatk-wrapper-java_0.33.3-22_all.deb ...
Unpacking libatk-wrapper-java (0.33.3-22) ...
Selecting previously unselected package libatk-wrapper-java-jni:armhf.
Preparing to unpack .../5-libatk-wrapper-java-jni_0.33.3-22_armhf.deb ...
Unpacking libatk-wrapper-java-jni:armhf (0.33.3-22) ...
Selecting previously unselected package openjdk-11-jre:armhf.
Preparing to unpack .../6-openjdk-11-jre_11.0.11+9-1~deb10u1_armhf.deb ...
Unpacking openjdk-11-jre:armhf (11.0.11+9-1~deb10u1) ...
Selecting previously unselected package spocon.
Preparing to unpack .../7-spocon_1.6.0_armhf.deb ...
Adding group `spocon' (GID 124) ...
Done.
Adding system user `spocon' (UID 115) ...
Adding new user `spocon' (UID 115) with group `spocon' ...
Creating home directory `/home/spocon' ...
Adding user `spocon' to group `audio' ...
Adding user spocon to group audio
Done.
Unpacking spocon (1.6.0) ...
Setting up java-common (0.71) ...
Setting up fonts-dejavu-extra (2.37-1) ...
Setting up libatk-wrapper-java (0.33.3-22) ...
Setting up libatk-wrapper-java-jni:armhf (0.33.3-22) ...
Setting up ca-certificates-java (20190405) ...
head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
Adding debian:DigiCert_Global_Root_CA.pem
Adding debian:thawte_Primary_Root_CA_-_G3.pem
Adding debian:Entrust_Root_Certification_Authority.pem
Adding debian:DigiCert_Assured_ID_Root_G3.pem
Adding debian:SSL.com_Root_Certification_Authority_ECC.pem
Adding debian:Izenpe.com.pem
Adding debian:GeoTrust_Universal_CA.pem
Adding debian:COMODO_RSA_Certification_Authority.pem
Adding debian:Go_Daddy_Root_Certificate_Authority_-_G2.pem
Adding debian:DigiCert_High_Assurance_EV_Root_CA.pem
Adding debian:ACCVRAIZ1.pem
Adding debian:USERTrust_ECC_Certification_Authority.pem
Adding debian:QuoVadis_Root_CA_2.pem
Adding debian:OISTE_WISeKey_Global_Root_GC_CA.pem
Adding debian:Buypass_Class_2_Root_CA.pem
Adding debian:DigiCert_Global_Root_G2.pem
Adding debian:emSign_ECC_Root_CA_-_G3.pem
Adding debian:QuoVadis_Root_CA_2_G3.pem
Adding debian:Entrust_Root_Certification_Authority_-_G4.pem
Adding debian:SZAFIR_ROOT_CA2.pem
Adding debian:GeoTrust_Primary_Certification_Authority.pem
Adding debian:T-TeleSec_GlobalRoot_Class_3.pem
Adding debian:NetLock_Arany_=Class_Gold=_F\u0151tan\u00fas\u00edtv\u00e1ny.pem
Adding debian:DigiCert_Trusted_Root_G4.pem
Adding debian:Security_Communication_RootCA2.pem
Adding debian:LuxTrust_Global_Root_2.pem
Adding debian:Go_Daddy_Class_2_CA.pem
Adding debian:T-TeleSec_GlobalRoot_Class_2.pem
Adding debian:QuoVadis_Root_CA.pem
Adding debian:GTS_Root_R3.pem
Adding debian:Chambers_of_Commerce_Root_-_2008.pem
Adding debian:IdenTrust_Commercial_Root_CA_1.pem
Adding debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.pem
Adding debian:Certum_Trusted_Network_CA_2.pem
Adding debian:Starfield_Services_Root_Certificate_Authority_-_G2.pem
Adding debian:AffirmTrust_Commercial.pem
Adding debian:GlobalSign_Root_CA.pem
Adding debian:TrustCor_ECA-1.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem
Adding debian:Certum_Trusted_Network_CA.pem
Adding debian:E-Tugra_Certification_Authority.pem
Adding debian:Global_Chambersign_Root_-_2008.pem
Adding debian:Certigna_Root_CA.pem
Adding debian:IdenTrust_Public_Sector_Root_CA_1.pem
Adding debian:GlobalSign_Root_CA_-_R6.pem
Adding debian:GeoTrust_Primary_Certification_Authority_-_G2.pem
Adding debian:TrustCor_RootCert_CA-2.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2015.pem
Adding debian:GeoTrust_Primary_Certification_Authority_-_G3.pem
Adding debian:Entrust.net_Premium_2048_Secure_Server_CA.pem
Adding debian:DigiCert_Assured_ID_Root_CA.pem
Adding debian:Sonera_Class_2_Root_CA.pem
Adding debian:AffirmTrust_Premium_ECC.pem
Adding debian:SecureSign_RootCA11.pem
Adding debian:emSign_Root_CA_-_C1.pem
Adding debian:ssl-cert-snakeoil.pem
Adding debian:DST_Root_CA_X3.pem
Adding debian:Atos_TrustedRoot_2011.pem
Adding debian:Network_Solutions_Certificate_Authority.pem
Adding debian:VeriSign_Universal_Root_Certification_Authority.pem
Adding debian:Comodo_AAA_Services_root.pem
Adding debian:Staat_der_Nederlanden_EV_Root_CA.pem
Adding debian:ePKI_Root_Certification_Authority.pem
Adding debian:TrustCor_RootCert_CA-1.pem
Adding debian:EC-ACC.pem
Adding debian:Trustis_FPS_Root_CA.pem
Adding debian:GlobalSign_Root_CA_-_R3.pem
Adding debian:Baltimore_CyberTrust_Root.pem
Adding debian:CFCA_EV_ROOT.pem
Adding debian:Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_ECC.pem
Adding debian:emSign_ECC_Root_CA_-_C3.pem
Adding debian:OISTE_WISeKey_Global_Root_GB_CA.pem
Adding debian:Staat_der_Nederlanden_Root_CA_-_G3.pem
Adding debian:COMODO_Certification_Authority.pem
Adding debian:Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.pem
Adding debian:Certigna.pem
Adding debian:CA_Disig_Root_R2.pem
Adding debian:Microsec_e-Szigno_Root_CA_2009.pem
Adding debian:thawte_Primary_Root_CA.pem
Adding debian:TeliaSonera_Root_CA_v1.pem
Adding debian:Amazon_Root_CA_2.pem
Adding debian:DigiCert_Assured_ID_Root_G2.pem
Adding debian:GlobalSign_Root_CA_-_R2.pem
Adding debian:Entrust_Root_Certification_Authority_-_EC1.pem
Adding debian:UCA_Extended_Validation_Root.pem
Adding debian:AC_RAIZ_FNMT-RCM.pem
Adding debian:Security_Communication_Root_CA.pem
Adding debian:TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem
Adding debian:TWCA_Root_Certification_Authority.pem
Adding debian:SecureTrust_CA.pem
Adding debian:AffirmTrust_Networking.pem
Adding debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G4.pem
Adding debian:thawte_Primary_Root_CA_-_G2.pem
Adding debian:emSign_Root_CA_-_G1.pem
Adding debian:Amazon_Root_CA_1.pem
Adding debian:DigiCert_Global_Root_G3.pem
Adding debian:certSIGN_ROOT_CA.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2011.pem
Adding debian:GDCA_TrustAUTH_R5_ROOT.pem
Adding debian:EE_Certification_Centre_Root_CA.pem
Adding debian:TWCA_Global_Root_CA.pem
Adding debian:Actalis_Authentication_Root_CA.pem
Adding debian:Entrust_Root_Certification_Authority_-_G2.pem
Adding debian:QuoVadis_Root_CA_1_G3.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R4.pem
Adding debian:Taiwan_GRCA.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_RSA_R2.pem
Adding debian:Secure_Global_CA.pem
Adding debian:GeoTrust_Global_CA.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R5.pem
Adding debian:ISRG_Root_X1.pem
Adding debian:Staat_der_Nederlanden_Root_CA_-_G2.pem
Adding debian:GTS_Root_R1.pem
Adding debian:GeoTrust_Universal_CA_2.pem
Adding debian:Starfield_Root_Certificate_Authority_-_G2.pem
Adding debian:SSL.com_Root_Certification_Authority_RSA.pem
Adding debian:USERTrust_RSA_Certification_Authority.pem
Adding debian:Starfield_Class_2_CA.pem
Adding debian:QuoVadis_Root_CA_3.pem
Adding debian:Amazon_Root_CA_3.pem
Adding debian:SwissSign_Silver_CA_-_G2.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem
Adding debian:AffirmTrust_Premium.pem
Adding debian:SwissSign_Gold_CA_-_G2.pem
Adding debian:Hongkong_Post_Root_CA_1.pem
Adding debian:GTS_Root_R4.pem
Adding debian:UCA_Global_G2_Root.pem
Adding debian:OISTE_WISeKey_Global_Root_GA_CA.pem
Adding debian:QuoVadis_Root_CA_3_G3.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_2009.pem
Adding debian:Amazon_Root_CA_4.pem
Adding debian:COMODO_ECC_Certification_Authority.pem
Adding debian:GTS_Root_R2.pem
Adding debian:Cybertrust_Global_Root.pem
Adding debian:XRamp_Global_CA_Root.pem
Adding debian:Hongkong_Post_Root_CA_3.pem
Adding debian:Buypass_Class_3_Root_CA.pem
done.
Processing triggers for fontconfig (2.13.1-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for ca-certificates (20200601~deb10u2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Setting up openjdk-11-jre-headless:armhf (11.0.11+9-1~deb10u1) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-armhf/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Setting up openjdk-11-jre:armhf (11.0.11+9-1~deb10u1) ...
Setting up spocon (1.6.0) ...
Created symlink /etc/systemd/system/multi-user.target.wants/spocon.service \u2192 /lib/systemd/system/spocon.service.
`

**Comment by devgianlu** [comment]
I assume you are running the default configuration, in this case you need to follow the instructions at https://github.com/librespot-org/librespot-java/tree/dev/player#zeroconf

**Comment by spocon** [comment]
Please try the new version 1.6.2 and let us know if that solves your problem

**Comment by spocon** [comment]
closing this..
