### ISSUE TITLE
Installation fails at fetching GPG key: dirmngr doesn't exist

### ISSUE THREAD

**Issue by Joennuh** [spocon/spocon#4]
**Describe the bug**
At fetching GPG key dirmngr failes to start because it doesn't exist.

**To Reproduce**
Issue occurs at normal installation and manual installation as described at README.md.
Manual installation steps:

1. Type in at the shell:
```shell
# Add repo and its GPG key
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7DBE8BF06EA39B78
```

2. The error will be: 
```shell
Executing: /tmp/apt-key-gpghome.oNCtAMY1b1/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 7DBE8BF06EA39B78
gpg: failed to start the dirmngr '/usr/bin/dirmngr': Bestand of map bestaat niet
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.oNCtAMY1b1/S.dirmngr' failed: Bestand of map bestaat niet
gpg: keyserver receive failed: Geen dirmngr
```
"Bestand of map bestaat niet" = "File or directory doesn't exist"
"Geen" = "No" or "None" 

3. Every step further will also fail.

**Expected behavior**
A good description of all steps needed to install SpoCon where installing the GPG key won't fail.

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 9 (stretch)

**Comment by spocon** [comment]
This seems gpg related. quick google search reveled this : https://blog.sleeplessbeastie.eu/2017/11/02/how-to-fix-missing-dirmngr/
