### ISSUE TITLE
randomly stops playing

### ISSUE THREAD

**Issue by RickyBurton** [spocon/spocon#40]
hi,
 spocon plays a few songs and stops, maybe one maybe ten so no consistent times, no clue what to to look at advice needed.

**Comment by devgianlu** [comment]
Can you share the logs?

**Comment by RickyBurton** [comment]
hello, where do I find them?

**Comment by MitraMai** [comment]
I have the same problem and been looking for the logs, but can't find them

**Comment by spocon** [comment]
run `journalctl -f -u spocon` in a terminal

**Comment by spocon** [comment]
if you want more logs run `journalctl -u spocon`
