### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by agneevX** [spocon/spocon#41]
Would be nice if this could be run in Docker.

**Comment by spocon** [comment]
its ongoing , but you can find it soon here: https://hub.docker.com/repository/docker/spocon/spocon#

**Comment by agneevX** [comment]
Thanks! I'd love multiarch support, if that's not already on your mind.

**Comment by spocon** [comment]
docker is ready 

@agneevX  currently i don't have the time to support that . Maybe later

**Comment by agneevX** [comment]
Thanks @spocon. Can you push a `latest` tag?

**Comment by spocon** [comment]
It's already pushed

**Comment by spocon** [comment]
Aha... Yes can do

**Comment by spocon** [comment]
done
