### ISSUE TITLE
Executing librespot java api fails

### ISSUE THREAD

**Issue by MikeLNo4** [spocon/spocon#42]
On a Raspi4 I followed the one-step installation command which ran without error. However Spocon does not show up in Spotify as device on IOS.

When checking with "service spocon status" I get the following: 
* spocon.service - SpoCon
   Loaded: loaded (/lib/systemd/system/spocon.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-11-06 23:05:24 CET; 2s ago
  Process: 1853 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
 Main PID: 1855 (java)
    Tasks: 19 (limit: 4915)
   CGroup: /system.slice/spocon.service
           `-1855 /usr/bin/java -jar /opt/spocon/librespot-java-api-v1.6.1.jar

Nov 06 23:05:24 pi4 systemd[1]: Starting SpoCon...
Nov 06 23:05:24 pi4 sh[1853]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Nov 06 23:05:24 pi4 sh[1853]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=15.9 ms
Nov 06 23:05:24 pi4 sh[1853]: --- spotify.com ping statistics ---
Nov 06 23:05:24 pi4 sh[1853]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Nov 06 23:05:24 pi4 sh[1853]: rtt min/avg/max/mdev = 15.910/15.910/15.910/0.000 ms
Nov 06 23:05:24 pi4 systemd[1]: Started SpoCon.

And then when Spotify goes searching for devices the status shows as follows:
* spocon.service - SpoCon
   Loaded: loaded (/lib/systemd/system/spocon.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-11-06 23:05:40 CET; 5s ago
  Process: 1882 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
  Process: 1884 ExecStart=/usr/bin/java -jar /opt/spocon/librespot-java-api-v1.6.1.jar (code=exited, status=1/FAILURE)
 Main PID: 1884 (code=exited, status=1/FAILURE)

Any idea what needs to be done here?

**Comment by spocon** [comment]
can you provide more input please `journalctl -u spocon`

**Comment by MikeLNo4** [comment]
There you go:


-- Logs begin at Tue 2022-01-04 13:28:51 CET, end at Tue 2022-01-04 13:31:05 CET. --
Jan 04 13:28:55 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:28:55 pi4 sh[493]: [60B blob data]
Jan 04 13:29:00 pi4 sh[493]: [60B blob data]
Jan 04 13:29:06 pi4 sh[493]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:29:06 pi4 sh[493]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=17.2 ms
Jan 04 13:29:06 pi4 sh[493]: --- spotify.com ping statistics ---
Jan 04 13:29:06 pi4 sh[493]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:29:06 pi4 sh[493]: rtt min/avg/max/mdev = 17.182/17.182/17.182/0.000 ms
Jan 04 13:29:06 pi4 systemd[1]: Started SpoCon.
Jan 04 13:29:12 pi4 java[963]: 2022-01-04 13:29:11,911 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:29:12 pi4 java[963]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:29:12 pi4 java[963]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:12 pi4 java[963]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1.
Jan 04 13:29:12 pi4 java[963]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:12 pi4 java[963]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:12 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:29:12 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:29:22 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:29:22 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 1.
Jan 04 13:29:22 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:29:22 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:29:22 pi4 sh[1153]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:29:22 pi4 sh[1153]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=22.2 ms
Jan 04 13:29:22 pi4 sh[1153]: --- spotify.com ping statistics ---
Jan 04 13:29:22 pi4 sh[1153]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:29:22 pi4 sh[1153]: rtt min/avg/max/mdev = 22.205/22.205/22.205/0.000 ms
Jan 04 13:29:22 pi4 systemd[1]: Started SpoCon.
Jan 04 13:29:25 pi4 java[1155]: 2022-01-04 13:29:25,141 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:29:25 pi4 java[1155]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:29:25 pi4 java[1155]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:25 pi4 java[1155]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:29:25 pi4 java[1155]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:25 pi4 java[1155]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:25 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:29:25 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:29:50 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:29:50 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 2.
Jan 04 13:29:50 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:29:50 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:29:50 pi4 sh[1181]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:29:50 pi4 sh[1181]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=17.2 ms
Jan 04 13:29:50 pi4 sh[1181]: --- spotify.com ping statistics ---
Jan 04 13:29:50 pi4 sh[1181]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:29:50 pi4 sh[1181]: rtt min/avg/max/mdev = 17.170/17.170/17.170/0.000 ms
Jan 04 13:29:50 pi4 systemd[1]: Started SpoCon.
Jan 04 13:29:53 pi4 java[1183]: 2022-01-04 13:29:53,720 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:29:53 pi4 java[1183]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:29:53 pi4 java[1183]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:53 pi4 java[1183]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:29:53 pi4 java[1183]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:53 pi4 java[1183]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:29:53 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:29:53 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:30:04 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:30:04 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 3.
Jan 04 13:30:04 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:30:04 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:30:04 pi4 sh[1205]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:30:04 pi4 sh[1205]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=17.2 ms
Jan 04 13:30:04 pi4 sh[1205]: --- spotify.com ping statistics ---
Jan 04 13:30:04 pi4 sh[1205]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:30:04 pi4 sh[1205]: rtt min/avg/max/mdev = 17.231/17.231/17.231/0.000 ms
Jan 04 13:30:04 pi4 systemd[1]: Started SpoCon.
Jan 04 13:30:07 pi4 java[1207]: 2022-01-04 13:30:06,978 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:30:07 pi4 java[1207]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:30:07 pi4 java[1207]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:07 pi4 java[1207]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:30:07 pi4 java[1207]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:07 pi4 java[1207]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:07 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:30:07 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:30:17 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:30:17 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 4.
Jan 04 13:30:17 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:30:17 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:30:17 pi4 sh[1229]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:30:17 pi4 sh[1229]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=19.2 ms
Jan 04 13:30:17 pi4 sh[1229]: --- spotify.com ping statistics ---
Jan 04 13:30:17 pi4 sh[1229]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:30:17 pi4 sh[1229]: rtt min/avg/max/mdev = 19.199/19.199/19.199/0.000 ms
Jan 04 13:30:17 pi4 systemd[1]: Started SpoCon.
Jan 04 13:30:20 pi4 java[1231]: 2022-01-04 13:30:20,261 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:30:20 pi4 java[1231]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:30:20 pi4 java[1231]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:20 pi4 java[1231]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:30:20 pi4 java[1231]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:20 pi4 java[1231]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:20 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:30:20 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:30:30 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:30:30 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 5.
Jan 04 13:30:30 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:30:30 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:30:35 pi4 sh[1253]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:30:35 pi4 sh[1253]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=15.9 ms
Jan 04 13:30:35 pi4 sh[1253]: --- spotify.com ping statistics ---
Jan 04 13:30:35 pi4 sh[1253]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:30:35 pi4 sh[1253]: rtt min/avg/max/mdev = 15.900/15.900/15.900/0.000 ms
Jan 04 13:30:35 pi4 systemd[1]: Started SpoCon.
Jan 04 13:30:38 pi4 java[1255]: 2022-01-04 13:30:38,558 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:30:38 pi4 java[1255]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:30:38 pi4 java[1255]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:38 pi4 java[1255]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:30:38 pi4 java[1255]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:38 pi4 java[1255]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:38 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:30:38 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:30:48 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:30:48 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 6.
Jan 04 13:30:48 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:30:48 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:30:48 pi4 sh[1316]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:30:48 pi4 sh[1316]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=16.7 ms
Jan 04 13:30:48 pi4 sh[1316]: --- spotify.com ping statistics ---
Jan 04 13:30:48 pi4 sh[1316]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:30:48 pi4 sh[1316]: rtt min/avg/max/mdev = 16.689/16.689/16.689/0.000 ms
Jan 04 13:30:48 pi4 systemd[1]: Started SpoCon.
Jan 04 13:30:51 pi4 java[1318]: 2022-01-04 13:30:51,711 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:30:51 pi4 java[1318]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:30:51 pi4 java[1318]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:51 pi4 java[1318]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:30:51 pi4 java[1318]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:51 pi4 java[1318]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:30:51 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:30:51 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.
Jan 04 13:31:02 pi4 systemd[1]: spocon.service: Service RestartSec=10s expired, scheduling restart.
Jan 04 13:31:02 pi4 systemd[1]: spocon.service: Scheduled restart job, restart counter is at 7.
Jan 04 13:31:02 pi4 systemd[1]: Stopped SpoCon.
Jan 04 13:31:02 pi4 systemd[1]: Starting SpoCon...
Jan 04 13:31:02 pi4 sh[1342]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
Jan 04 13:31:02 pi4 sh[1342]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=115 time=16.3 ms
Jan 04 13:31:02 pi4 sh[1342]: --- spotify.com ping statistics ---
Jan 04 13:31:02 pi4 sh[1342]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jan 04 13:31:02 pi4 sh[1342]: rtt min/avg/max/mdev = 16.321/16.321/16.321/0.000 ms
Jan 04 13:31:02 pi4 systemd[1]: Started SpoCon.
Jan 04 13:31:05 pi4 java[1344]: 2022-01-04 13:31:05,037 ERROR Log4JUncaughtExceptionHandler:31 - [main]
Jan 04 13:31:05 pi4 java[1344]: java.lang.IllegalArgumentException: Device ID must be 40 chars long.
Jan 04 13:31:05 pi4 java[1344]:         at xyz.gianlu.librespot.core.Session$AbsBuilder.setDeviceId(Session.java:857) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:31:05 pi4 java[1344]:         at xyz.gianlu.librespot.player.FileConfiguration.initZeroconfBuilder(FileConfiguration.java:364) ~[librespot-java-api-v1.6.1.jar:1
Jan 04 13:31:05 pi4 java[1344]:         at xyz.gianlu.librespot.api.Main.withPlayer(Main.java:51) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:31:05 pi4 java[1344]:         at xyz.gianlu.librespot.api.Main.main(Main.java:45) ~[librespot-java-api-v1.6.1.jar:1.6.1]
Jan 04 13:31:05 pi4 systemd[1]: spocon.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 13:31:05 pi4 systemd[1]: spocon.service: Failed with result 'exit-code'.

**Comment by MikeLNo4** [comment]
Hey @spocon.
Any potential you could have a look at this? Do you need some more information I can help with?
Best,
M.

**Comment by devgianlu** [comment]
It looks like the Device ID is being set incorrectly to a string that isn't the correct length. If the Device ID is empty is should be automatically generated.

**Comment by MikeLNo4** [comment]
Indeed. That worked like a charm. Thanks a lot!!
