### ISSUE TITLE
Multiple instances of spocom on the same machine with different configurations?

### ISSUE THREAD

**Issue by nadigo** [spocon/spocon#44]
Can you run multiple instances of spocom on the same machine with different configurations?

**Comment by spocon** [comment]
yes , the easiest way is to configure one specific port in the config.toml and run it in a docker instance. The service file can map the ports accordingly

**Comment by spocon** [comment]
Im working on a docker instance currently , you can follow it here : https://github.com/spocon/spocon/issues/41
