### ISSUE TITLE
permission denied when using PIPE

### ISSUE THREAD

**Issue by Kwinnieprince** [spocon/spocon#45]
**Describe the bug**
Pemission denied in Pipe

**To Reproduce**
Start the server on a place where you have access

**Expected behavior**
No permission denied for places where there is access

**Screenshots**

**Logs**
`Feb 16 12:35:16 raspberrypi java[6359]: 2022-02-16 12:35:16,047 DEBUG Player:106 - Received command: Transfer
Feb 16 12:35:16 raspberrypi java[6359]: 2022-02-16 12:35:16,727 DEBUG Player:533 - Loading context (transfer), uri: spotify:playlist:37i9dQZF1E39WNWQOVPYeb
Feb 16 12:35:16 raspberrypi java[6359]: 2022-02-16 12:35:16,867 DEBUG DeviceStateHandler:210 - Device is now active. {ts: 1645014916876}
Feb 16 12:35:16 raspberrypi java[6359]: 2022-02-16 12:35:16,994 TRACE StateWrapper:1139 - Initialized current track index to 4.
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,047 DEBUG Player:348 - Loading session, id: b37iKNKVmg8NbyH5TjhTRw, play: false
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,111 INFO  PlayerSession:69 - Created new session. {id: b37iKNKVmg8NbyH5TjhTRw}
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,154 DEBUG Player:490 - Loading track, id: TrackId{spotify:track:4iaaEAAyCWrQdYT5tRnyDb}, session: b37iKNKVmg8NbyH5TjhTRw, playback: null, play: false
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,188 TRACE MercuryClient:156 - Send Mercury request, seq: 2, uri: hm://event-service/v1/events, method: POST
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,233 TRACE PlayerQueueEntry:92 - Created new PlayerQueueEntry{0152fa8147c9b0926222b1f3caf2a1fb}.
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,238 TRACE PlayerSession:162 - PlayerQueueEntry{0152fa8147c9b0926222b1f3caf2a1fb} started loading.
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,238 TRACE PlayerQueue:82 - PlayerQueueEntry{0152fa8147c9b0926222b1f3caf2a1fb} added to queue.
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,245 DEBUG PlayerSession:283 - PlayerQueueEntry{0152fa8147c9b0926222b1f3caf2a1fb} has been added to the output. {sessionId: b37iKNKVmg8NbyH5TjhTRw, pos: 78124, reason: CLICK_ROW}
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,256 TRACE MercuryClient:199 - Handling packet, cmd: MercuryReq, seq: 2, flags: 1, parts: 1
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,260 DEBUG EventService:51 - Event sent. {body: 557|3|b37iKNKVmg8NbyH5TjhTRw|spotify:playlist:37i9dQZF1E39WNWQOVPYeb|spotify:playlist:37i9dQZF1E39WNWQOVPYeb|1645014917149||50|context://spotify:playlist:37i9dQZF1E39WNWQOVPYeb, result: 200}
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,264 TRACE MercuryClient:156 - Send Mercury request, seq: 3, uri: hm://event-service/v1/events, method: POST
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,368 TRACE MercuryClient:199 - Handling packet, cmd: MercuryReq, seq: 3, flags: 1, parts: 1
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,371 DEBUG EventService:51 - Event sent. {body: 558|1|0152fa8147c9b0926222b1f3caf2a1fb|b37iKNKVmg8NbyH5TjhTRw|1645014917266, result: 200}
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,399 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:17 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:17 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:17 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:17 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:17 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:60) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:56) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendPipeFlush(DacpMetadataPipe.java:110) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onPlaybackPaused(Player.java:992) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$playbackPaused$2(Player.java:1068) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:17 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:17 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:17 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Feb 16 12:35:17 raspberrypi java[6359]: 2022-02-16 12:35:17,433 DEBUG DealerClient:126 - Handled request. {key: 227d2810-5dbd-4f67-a425-9a2ac686a5d2, result: SUCCESS}

// discared since too long //

Feb 16 12:35:18 raspberrypi java[6359]: 2022-02-16 12:35:18,934 TRACE CdnManager:277 - Chunk 22/85 completed, cached: true, stream: {fileId: 1D58D0861AF16DEAC30E498408FCF9207E7BEAD4}
Feb 16 12:35:18 raspberrypi java[6359]: 2022-02-16 12:35:18,934 TRACE CdnManager:277 - Chunk 23/85 completed, cached: true, stream: {fileId: 1D58D0861AF16DEAC30E498408FCF9207E7BEAD4}
Feb 16 12:35:18 raspberrypi java[6359]: 2022-02-16 12:35:18,939 TRACE PlayerSession:194 - PlayerQueueEntry{0152fa8147c9b0926222b1f3caf2a1fb} finished loading.
Feb 16 12:35:18 raspberrypi java[6359]: 2022-02-16 12:35:18,940 TRACE CdnManager:277 - Chunk 24/85 completed, cached: true, stream: {fileId: 1D58D0861AF16DEAC30E498408FCF9207E7BEAD4}
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,051 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:19 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:60) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:56) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendPipeFlush(DacpMetadataPipe.java:110) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onFinishedLoading(Player.java:1054) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$finishedLoading$6(Player.java:1092) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,062 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:19 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:60) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendTrackInfo(DacpMetadataPipe.java:96) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onMetadataAvailable(Player.java:1018) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$metadataAvailable$10(Player.java:1121) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,069 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:19 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:60) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendTrackInfo(DacpMetadataPipe.java:97) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onMetadataAvailable(Player.java:1018) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$metadataAvailable$10(Player.java:1121) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,085 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:19 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:60) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendTrackInfo(DacpMetadataPipe.java:98) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onMetadataAvailable(Player.java:1018) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$metadataAvailable$10(Player.java:1121) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,090 TRACE MixingLine:184 - Toggle first channel: true
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,394 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:19 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:60) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendProgress(DacpMetadataPipe.java:92) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onMetadataAvailable(Player.java:1022) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$metadataAvailable$10(Player.java:1121) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Feb 16 12:35:19 raspberrypi java[6359]: 2022-02-16 12:35:19,934 INFO  DeviceStateHandler:273 - Put state. {ts: 1645014919040, connId: MmM2N...FRTg0, reason: PLAYER_STATE_CHANGED, request: device { device_info { can_play: true volume: 5243 name: 
Feb 16 12:35:20 raspberrypi java[6359]: 2022-02-16 12:35:20,165 ERROR DacpMetadataPipe:67 - Failed sending metadata through pipe!
Feb 16 12:35:20 raspberrypi java[6359]: java.io.FileNotFoundException: /home/pi/music/spotify/spotify.metadata (Permission denied)
Feb 16 12:35:20 raspberrypi java[6359]:         at java.io.FileOutputStream.open0(Native Method) ~[?:?]
Feb 16 12:35:20 raspberrypi java[6359]:         at java.io.FileOutputStream.open(FileOutputStream.java:298) ~[?:?]
Feb 16 12:35:20 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[?:?]
Feb 16 12:35:20 raspberrypi java[6359]:         at java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[?:?]
Feb 16 12:35:20 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.send(DacpMetadataPipe.java:72) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:20 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.safeSend(DacpMetadataPipe.java:65) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:20 raspberrypi java[6359]:         at xyz.gianlu.librespot.dacp.DacpMetadataPipe.sendImage(DacpMetadataPipe.java:88) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:20 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher$1.onMetadataAvailable(Player.java:1025) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:20 raspberrypi java[6359]:         at xyz.gianlu.librespot.player.Player$EventsDispatcher.lambda$metadataAvailable$10(Player.java:1121) ~[librespot-java-api-v1.6.2.jar:1.6.2]
Feb 16 12:35:20 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Feb 16 12:35:20 raspberrypi java[6359]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Feb 16 12:35:20 raspberrypi java[6359]:         at java.lang.Thread.run(Thread.java:829) [?:?]`

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: IOS 15.3

**Additional context**

**Comment by spocon** [comment]
Cant help here, I recommend to open an issue to librespot-java project
