### ISSUE TITLE
Spotify does not see spocon spotify-connect

### ISSUE THREAD

**Issue by iVolt1** [spocon/spocon#46]
**Describe the bug**

Spotify on my windows 10 desktop and iphone 7 can not see spocon as a spotify-connect server.  When running raspotify on the same device I can connect to librespot every time from spotify on the desktop and iphone.

Below is the service log and the config.toml.  Config.toml is configured to ouptut audio and metedata to pipe to owntone.

Spocon is (and librespot for testing as needed) running on Dietpi 8.1 x86.

Thanks for the great project and helping with this bug.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone7]
 - OS:15.3.1

**Logs**
If applicable, execute `journalctl -u spocon -f --no-pager` and paste the result here.
root@DietPi:/opt/spocon# systemctl -n 1000 status spocon
● spocon.service - SpoCon
     Loaded: loaded (/lib/systemd/system/spocon.service; disabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-02-26 06:04:01 CST; 10s ago
    Process: 121732 ExecStartPre=/bin/sh -c until ping -c1 spotify.com; do sleep 5; done; (code=exited, status=0/SUCCESS)
   Main PID: 121734 (java)
      Tasks: 19 (limit: 1164)
     Memory: 49.9M
        CPU: 1.587s
     CGroup: /system.slice/spocon.service
             └─121734 /usr/bin/java -jar /opt/spocon/librespot-java-api-v1.6.2.jar

Feb 26 06:04:01 DietPi systemd[1]: Starting SpoCon...
Feb 26 06:04:01 DietPi sh[121733]: PING spotify.com(2600:1901:1:c36:: (2600:1901:1:c36::)) 56 data bytes
Feb 26 06:04:01 DietPi sh[121733]: 64 bytes from 2600:1901:1:c36:: (2600:1901:1:c36::): icmp_seq=1 ttl=118 time=3.97 ms
Feb 26 06:04:01 DietPi sh[121733]: --- spotify.com ping statistics ---
Feb 26 06:04:01 DietPi sh[121733]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Feb 26 06:04:01 DietPi sh[121733]: rtt min/avg/max/mdev = 3.972/3.972/3.972/0.000 ms
Feb 26 06:04:01 DietPi systemd[1]: Started SpoCon.
Feb 26 06:04:02 DietPi java[121734]: 2022-02-26 06:04:02,506 INFO  Utils:104 - Cryptography restrictions removal not needed.
Feb 26 06:04:02 DietPi java[121734]: 2022-02-26 06:04:02,549 INFO  ZeroconfServer:472 - Zeroconf HTTP server started successfully on port 58550!
Feb 26 06:04:03 DietPi java[121734]: 2022-02-26 06:04:03,991 INFO  Zeroconf:500 - Announced Service{alias='librespot', service='spotify-connect', port=58550, text={                                                                         VERSION=1.0, CPath=/, Stack=SP}, addresses=[], domain='.local', protocol='tcp', host='DietPi'}.
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,005 DEBUG logging:152 - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,093 INFO  undertow:120 - starting server: Undertow - 2.2.14.Final
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,099 INFO  xnio:95 - XNIO version 3.8.4.Final
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,114 INFO  nio:58 - XNIO NIO Implementation Version 3.8.4.Final
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,115 TRACE nio:176 - Starting up with selector provider class sun.nio.ch.EPollSelectorProvider
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,116 TRACE nio:219 - Using Default system selector creator for provider class sun.nio.ch.EPollSelectorProvid                                                                         er for main selectors and Default system selector creator for provider class sun.nio.ch.EPollSelectorProvider for temp selectors
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,133 INFO  threads:52 - JBoss Threads version 3.1.0.Final
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,141 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@7103cb56 00000001 -> 00000002
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,141 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@7103cb56 00000002 -> 00000003
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,142 TRACE nio:440 - Starting worker thread Thread[XNIO-1 I/O-1,5,main]
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,143 DEBUG nio:444 - Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.EPollSelectorImpl@4bddc78
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,143 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@4bddc78
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,143 TRACE nio:531 - Select, queue is empty
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,143 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@7103cb56 00000003 -> 00000004
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,144 TRACE nio:440 - Starting worker thread Thread[XNIO-1 I/O-2,5,main]
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,144 DEBUG nio:444 - Started channel thread 'XNIO-1 I/O-2', selector sun.nio.ch.EPollSelectorImpl@48fb700e
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,145 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@48fb700e
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,145 TRACE nio:531 - Select, queue is empty
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,146 DEBUG undertow:160 - Configuring listener with protocol HTTP for interface 0.0.0.0 and port 24879
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,153 TRACE nio:440 - Starting worker thread Thread[XNIO-1 Accept,5,main]
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,153 DEBUG nio:444 - Started channel thread 'XNIO-1 Accept', selector sun.nio.ch.EPollSelectorImpl@10943ce2
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,154 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@10943ce2
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,154 TRACE nio:531 - Select, queue is empty
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,177 TRACE selector:564 - Selected on sun.nio.ch.EPollSelectorImpl@10943ce2
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,177 TRACE nio:611 - Running task org.xnio.nio.WorkerThread$SynchTask@1e53d080
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,179 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@10943ce2
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,179 TRACE nio:531 - Select, queue is empty
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,184 TRACE listener:57 - Setting channel listener to org.xnio.nio.QueuedNioTcpServer2$$Lambda$153/0x00000008                                                                         401e0c40@35e5d0e5
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,188 TRACE nio:624 - Added task org.xnio.nio.NioTcpServerHandle$2@77d2e85
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,188 TRACE selector:564 - Selected on sun.nio.ch.EPollSelectorImpl@10943ce2
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,188 TRACE nio:611 - Running task org.xnio.nio.NioTcpServerHandle$2@77d2e85
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,188 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@10943ce2
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,188 TRACE nio:531 - Select, queue is empty
Feb 26 06:04:04 DietPi java[121734]: 2022-02-26 06:04:04,189 INFO  ApiServer:65 - Server started on port 24879!
root@DietPi:/opt/spocon#

**Additional context**
/opt/spocon/config.toml

### Device type (COMPUTER, TABLET, SMARTPHONE, SPEAKER, TV, AVR, STB, AUDIO_DONGLE, GAME_CONSOLE, CAST_VIDEO, CAST_AUDIO, AUTOMOBILE, WEARABLE, UNKNOWN_SPOTIFY, CAR_THING, UNKNOWN) ###
deviceType = "AVR"
### Device name ###
deviceName = "librespot"
### Device ID (40 chars, leave empty for random)  ###
deviceId = ""
### Log level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL) ###
logLevel = "ALL"

### Preferred locale ###
preferredLocale = "en"

### Cache ###
[cache]
        dir = "./cache/"
        # Cache enabled
        enabled = true
        doCleanUp = true

### Authentication ###
[auth]
        # Credentials file (JSON)
        credentialsFile = "credentials.json"
        # Spotify password (USER_PASS only)
        password = ""
        # Spotify authentication blob Base64-encoded (BLOB only)
        blob = ""
        # Whether to store reusable credentials on disk (not a plain password)
        storeCredentials = false
        # Strategy (USER_PASS, ZEROCONF, BLOB, FACEBOOK, STORED)
        strategy = "ZEROCONF"
        # Spotify username (BLOB, USER_PASS only)
        username = ""

### Preload ###
[preload]
        # Preload enabled
        enabled = true

### Network ###
[network]
        # If ping isn't received within this amount of seconds, reconnect
        connectionTimeout = 10

### Proxy ###
[proxy]
        # Basic auth password
        password = ""
        # The proxy hostname
        address = ""
        # The proxy port
        port = 0
        # Whether authentication is enabled on the server
        auth = false
        # The proxy type (HTTP, SOCKS)
        type = "HTTP"
        # Connect to proxy using SSL (HTTP only)
        ssl = false
        # Whether the proxy is enabled
        enabled = false
        # Basic auth username
        username = ""

### Zeroconf ###
[zeroconf]
        # Listen on all interfaces (overrides `zeroconf.interfaces`)
        listenAll = true
        # Listen on these interfaces (comma separated list of names)
        interfaces = ""
        # Listen on this TCP port (`-1` for random)
        listenPort = -1
# 5353

### Shell ###
[shell]
        onTrackSeeked = ""
        onStartedLoading = ""
        onConnectionDropped = ""
        onMetadataAvailable = ""
        onTrackChanged = ""
        onPanicState = ""
        onFinishedLoading = ""
        # Shell events enabled
        enabled = false
        onPlaybackResumed = ""
        onConnectionEstablished = ""
        onPlaybackEnded = ""
        onContextChanged = ""
        # Execute the command with `bash -c`
        executeWithBash = false
        onPlaybackPaused = ""
        onInactiveSession = ""
        onVolumeChanged = ""

### Time correction ###
[time]
        # Manual time correction in millis
        manualCorrection = 0
        # Time synchronization method (NTP, PING, MELODY, MANUAL)
        synchronizationMethod = "NTP"

### API ###
[api]
        # API port (`api` module only)
        port = 24879
        # API listen interface (`api` module only)
        host = "0.0.0.0"

### Player ###
[player]
        # Whether to apply the Spotify loudness normalisation
        enableNormalisation = true
        # Initial volume (0-65536)
        initialVolume = 65536
        # Whether librespot-java should ignore volume events, sink volume is set to the max
        bypassSinkVolume = false
        # Release mixer line after set delay (in seconds)
        releaseLineDelay = 20
        # Normalisation pregain in decibels (loud at +6, normal at +3, quiet at -5)
        normalisationPregain = 3.0
        # Output metadata in Shairport Sync format (https://github.com/mikebrady/shairport-sync-metadata-reader)
        metadataPipe = "/srv/music/spotify.metadata"
        # Autoplay similar songs when your music ends
        autoplayEnabled = true
        # Preferred audio quality (NORMAL, HIGH, VERY_HIGH)
        preferredAudioQuality = "NORMAL"
        # Where librespot-java should search for local files
        localFilesPath = ""
        # Audio output device (MIXER, PIPE, STDOUT, CUSTOM)
        output = "PIPE"
        # Crossfade overlap time (in milliseconds)
        crossfadeDuration = 0
        # Audio output Java class name
        outputClass = ""
        # Whether the player should retry fetching a chuck if it fails
        retryOnChunkError = true
        # Mixer/backend search keywords (semicolon separated)
        mixerSearchKeywords = ""
        # Output raw (signed) PCM to this file (`player.output` must be PIPE)
        pipe = "/srv/music/spotify"
        # Number of volume notches
        volumeSteps = 64
        # Log available mixers
        logAvailableMixers = true

**Comment by iVolt1** [comment]
I am running spocon in a virtualbox VM.  It looks like this code excludes running VMs, possibly for now good reason.  I changed the x08 to x06the MAC in the VM settings and now spotify connects to spocon.

https://github.com/librespot-org/librespot-java/blob/dev/lib/src/main/java/xyz/gianlu/librespot/ZeroconfServer.java

...
public class ZeroconfServer implements Closeable {
    public static final String SERVICE = "spotify-connect";
    private final static int MAX_PORT = 65536;
    private final static int MIN_PORT = 1024;
    private static final Logger LOGGER = LoggerFactory.getLogger(ZeroconfServer.class);
    private static final byte[] EOL = new byte[]{'\r', '\n'};
    private static final JsonObject DEFAULT_GET_INFO_FIELDS = new JsonObject();
    private static final JsonObject DEFAULT_SUCCESSFUL_ADD_USER = new JsonObject();
    private static final byte[][] VIRTUAL_INTERFACES = new byte[][]{
            new byte[]{(byte) 0x00, (byte) 0x0F, (byte) 0x4B}, // Virtual Iron Software, Inc.
            new byte[]{(byte) 0x00, (byte) 0x13, (byte) 0x07}, // Paravirtual Corporation
            new byte[]{(byte) 0x00, (byte) 0x13, (byte) 0xBE}, // Virtual Conexions
            new byte[]{(byte) 0x00, (byte) 0x21, (byte) 0xF6}, // Virtual Iron Software
            new byte[]{(byte) 0x00, (byte) 0x24, (byte) 0x0B}, // Virtual Computer Inc.
            new byte[]{(byte) 0x00, (byte) 0xA0, (byte) 0xB1}, // First Virtual Corporation
            new byte[]{(byte) 0x00, (byte) 0xE0, (byte) 0xC8}, // Virtual access, ltd.
            new byte[]{(byte) 0x54, (byte) 0x52, (byte) 0x00}, // Linux kernel virtual machine (kvm)
            new byte[]{(byte) 0x00, (byte) 0x21, (byte) 0xF6}, // Oracle Corporation
            new byte[]{(byte) 0x18, (byte) 0x92, (byte) 0x2C}, // Virtual Instruments
            new byte[]{(byte) 0x3C, (byte) 0xF3, (byte) 0x92}, // VirtualTek. Co. Ltd.
            new byte[]{(byte) 0x00, (byte) 0x05, (byte) 0x69}, // VMWare 1
            new byte[]{(byte) 0x00, (byte) 0x0C, (byte) 0x29}, // VMWare 2
            new byte[]{(byte) 0x00, (byte) 0x50, (byte) 0x56}, // VMWare 3
            new byte[]{(byte) 0x00, (byte) 0x1C, (byte) 0x42}, // Parallels
            new byte[]{(byte) 0x00, (byte) 0x03, (byte) 0xFF}, // Microsoft Virtual PC
            new byte[]{(byte) 0x00, (byte) 0x16, (byte) 0x3E}, // Red Hat Xen, Oracle VM, Xen Source, Novell Xen
            **new byte[]{(byte) 0x08, (byte) 0x00, (byte) 0x27}, // VirtualBox**
            new byte[]{(byte) 0x00, (byte) 0x15, (byte) 0x5D}, // Hyper-V
    };
...

**Comment by devgianlu** [comment]
The check is in place to avoid dispatching to virtual interfaces from the host, but I guess it's the same MAC for the guest.
