### ISSUE TITLE
audio-sink not visible to spotify's familiy members

### ISSUE THREAD

**Issue by franconianmetal** [spocon/spocon#48]
**Describe the bug**
 
as main login'ed and registered spotify-user I can see spocon as audio sink
but other familiy members using this account as added users can not see spocon

Is there a way to set this availability of spocon to any account-assigned user?

besides: Many thanks for providing this, this helps me bypassing this painful cut of spotify's api described [here](https://github.com/mopidy/mopidy-spotify/issues/110)

**To Reproduce**
grab familiy's device and search for spocon

**Expected behavior**
spocon audio-sink is available for all members assigned to the account

**Screenshots**
none, cause useless

**Logs**
none

**Desktop (please complete the following information):**
 - OS: spocon deployed on proxmox-container, 
 PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

**Smartphone (please complete the following information):**
 - Device: any android device for family-member or main-account and vice versa

**Additional context**
none

**Comment by spocon** [comment]
Please open a ticket here : https://github.com/librespot-org/librespot-java
